spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: admin
  application:
    name: tripcut-api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tripcut
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      enabled: false
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: TripCutScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.H2Delegate
            tablePrefix: QRTZ_
            isClustered: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: uydRcRuRxXNOif8BrERtQb7aAteuzxqn
  expiration: 86400000 # 24시간

fastapi:
  base-url: http://localhost:8000

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.tripcut: DEBUG
    org.springframework.batch: DEBUG
    org.quartz: DEBUG
  file:
    name: /var/log/spring-boot/tripcut-api.log
    max-size: 10MB
    max-history: 7 